### ISSUE TITLE
连怎么跑起来都不知道

### ISSUE THREAD

**Issue by zxzxac110** [infinityu/mina-wear-mask#1]
默默的说 我连怎么跑起来都不知道

**Comment by shanjixiaboss** [comment]
> 默默的说 我连怎么跑起来都不知道

hbuilder编辑器导进去,先看下uniapp文档

**Comment by laoniubit** [comment]
1，是用微信的云开发后台么？
2，小程序的服务器域名，业务域名，消息推送这么设置？
